/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package fuzzycmeanassignment;

import fuzzycmeanassignment.algorithm.ExtendPoint;
import fuzzycmeanassignment.algorithm.Fuzzy_C_Means_Demo;
import fuzzycmeanassignment.algorithm.Point;
import fuzzycmeanassignment.file.FileProccess;
import fuzzycmeanassignment.jogl.Renderer;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.io.File;
import javax.media.opengl.GLCapabilities;
import javax.media.opengl.GLProfile;
import javax.media.opengl.awt.GLCanvas;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author kubin
 */
public class FuzzyCMeanFrame extends javax.swing.JFrame {

    public static final String[] COL_NAMES = {"ID", "X", "Y", "Z", "Color"};
    private Renderer render;
    /**
     * Creates new form FuzzyCMeanFrame
     */
    public FuzzyCMeanFrame() {
	initComponents();
	spinCluster.setValue(new Integer(5));
	GLProfile glp = GLProfile.get(GLProfile.GL2);
	GLCapabilities glc = new GLCapabilities(glp);

	canvas = new GLCanvas(glc);
	canvas.setPreferredSize(new Dimension(panelJogl.getWidth(), panelJogl.getHeight()));
	canvas.setBounds(0, 0, panelJogl.getWidth(), panelJogl.getHeight());
	render = new Renderer(canvas);
	canvas.addGLEventListener(render);

	panelJogl.add(canvas);

	fcm = new Fuzzy_C_Means_Demo();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelJogl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtInputFile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnInputChoose = new javax.swing.JButton();
        btnRun = new javax.swing.JButton();
        spinCluster = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMValue = new javax.swing.JTextField();
        txtEpsilon = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnExport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCluster = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kây Bi Fuzzy C-Mean Demo");
        setPreferredSize(new java.awt.Dimension(1024, 668));

        panelJogl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelJogl.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                panelJoglComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panelJoglLayout = new javax.swing.GroupLayout(panelJogl);
        panelJogl.setLayout(panelJoglLayout);
        panelJoglLayout.setHorizontalGroup(
            panelJoglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        panelJoglLayout.setVerticalGroup(
            panelJoglLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtInputFile.setToolTipText("");

        jLabel1.setText("Input");

        btnInputChoose.setText("Browse");
        btnInputChoose.setToolTipText("Please choose input file");
        btnInputChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputChooseActionPerformed(evt);
            }
        });

        btnRun.setText("Run");
        btnRun.setToolTipText("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        spinCluster.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinClusterStateChanged(evt);
            }
        });

        jLabel2.setText("Number of cluster");

        jLabel3.setText("m value");

        txtMValue.setText("2.0");

        txtEpsilon.setText("0.00001");

        jLabel5.setText("Epsilon");

        btnExport.setText("Export");
        btnExport.setToolTipText("Export data to file");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtInputFile))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinCluster, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEpsilon)
                            .addComponent(txtMValue)
                            .addComponent(btnInputChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnInputChoose))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinCluster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtMValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEpsilon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExport)
                .addContainerGap())
        );

        tblCluster.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "X", "Y", "Z", "Color"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCluster.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblCluster);
        tblCluster.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCluster.getColumnModel().getColumn(0).setMinWidth(30);
        tblCluster.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblCluster.getColumnModel().getColumn(0).setMaxWidth(30);
        tblCluster.getColumnModel().getColumn(4).setMinWidth(40);
        tblCluster.getColumnModel().getColumn(4).setPreferredWidth(40);
        tblCluster.getColumnModel().getColumn(4).setMaxWidth(40);

        jLabel4.setText("Cluster(s)");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4))
                        .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelJogl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelJogl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRefresh)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputChooseActionPerformed
	if (chooserFileOpen == null) {
	    chooserFileOpen = new JFileChooser();

	}

	if (fileInput != null) {
	    chooserFileOpen.setCurrentDirectory(fileInput.getParentFile());
	}

	chooserFileOpen.showOpenDialog(this);
	File tmp = chooserFileOpen.getSelectedFile();

	if (tmp != null) {
	    fileInput = tmp;
	    txtInputFile.setText(fileInput.getAbsolutePath());
	}

    }//GEN-LAST:event_btnInputChooseActionPerformed

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
	if (chooserFileSave == null) {
	    chooserFileSave = new JFileChooser();
	}
	if (fileOutput != null) {
	    chooserFileSave.setCurrentDirectory(fileOutput.getParentFile());
	}
	chooserFileSave.showSaveDialog(this);
	fileOutput = chooserFileSave.getSelectedFile();
	if (fileOutput != null) {
	    //TODO save data to file Output
	}


    }//GEN-LAST:event_btnExportActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
	// TODO add your handling code here:
	if (fileInput == null) {
	    JOptionPane.showMessageDialog(this, "Please choose input file first", "Error",
		    JOptionPane.ERROR_MESSAGE);
	    txtInputFile.requestFocus();
	} else {
	    if (fileProccess == null) {
		fileProccess = new FileProccess();
	    }
	    points = fileProccess.readFile(fileInput);
	    pMin = fileProccess.pMin;
	    pMax = fileProccess.pMax;
	    String strMValue = txtMValue.getText();
	    String strEpsilon = txtEpsilon.getText();

	    try {
		mValue = Double.parseDouble(strMValue);

	    } catch (Exception e) {
		JOptionPane.showMessageDialog(this, "Please enter valid number", "Error",
			JOptionPane.ERROR_MESSAGE);
		txtMValue.requestFocus();
		txtMValue.setSelectionStart(0);
		return;
	    }
	    try {
		epsilon = Double.parseDouble(strEpsilon);
	    } catch (Exception e) {
		JOptionPane.showMessageDialog(this, "Please enter valid number", "Error",
			JOptionPane.ERROR_MESSAGE);
		txtEpsilon.requestFocus();
		txtEpsilon.setSelectionStart(0);
		return;
	    }
	    numberOfCluster = (Integer) spinCluster.getValue();
	    setCursor(Cursor.WAIT_CURSOR);
	    btnRun.disable();
	    reSolve();
	    setCursor(Cursor.DEFAULT_CURSOR);
	    btnRun.enable();

	}

    }//GEN-LAST:event_btnRunActionPerformed

    private void reSolve() {
	
	fcm.reset(points, numberOfCluster, mValue);
	fcm.run(epsilon);
	clusters = fcm.getClusters();

	DefaultTableModel model = new DefaultTableModel(COL_NAMES, 0);

	tblCluster.setDefaultRenderer(Object.class, new CustomRender(clusters));

	tblCluster.setModel(model);
	for (int i = 0; i < clusters.length; i++) {
	    model.addRow(clusters[i].toObject(i + 1));

	}

	TableColumnModel colModel = tblCluster.getColumnModel();
	colModel.getColumn(0).setPreferredWidth(30);
	colModel.getColumn(4).setPreferredWidth(40);

	int midWidth = (tblCluster.getWidth() - 70) / 3;
	for (int i = 1; i < 4; i++) {
	    colModel.getColumn(i).setPreferredWidth(midWidth);
	}
	System.out.println("reSolve : points length = " + points.length);
	render.reset(points, clusters, pMin, pMax);


    }

    private void spinClusterStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinClusterStateChanged
	int nc = (Integer) spinCluster.getValue();
	if (nc <= 0) {
	    spinCluster.setValue(1);
	}
    }//GEN-LAST:event_spinClusterStateChanged

    private void panelJoglComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelJoglComponentResized
	if (canvas != null) {
	    canvas.setBounds(0, 0, panelJogl.getWidth(), panelJogl.getHeight());
	}
    }//GEN-LAST:event_panelJoglComponentResized

    /**
	 * @param args the command line arguments
	 */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(FuzzyCMeanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(FuzzyCMeanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(FuzzyCMeanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(FuzzyCMeanFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    @Override
	    public void run() {
		new FuzzyCMeanFrame().setVisible(true);
	    }
	});
    }
    private JFileChooser chooserFileOpen;
    private JFileChooser chooserFileSave;
    private File fileInput;
    private File fileOutput;
    private FileProccess fileProccess;
    private ExtendPoint[] points;
    private ExtendPoint[] clusters;
    private Point pMin, pMax;
    private int numberOfCluster;
    private double mValue;
    private double epsilon;
    private GLCanvas canvas;
    private Fuzzy_C_Means_Demo fcm;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnInputChoose;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelJogl;
    private javax.swing.JSpinner spinCluster;
    private javax.swing.JTable tblCluster;
    private javax.swing.JTextField txtEpsilon;
    private javax.swing.JTextField txtInputFile;
    private javax.swing.JTextField txtMValue;
    // End of variables declaration//GEN-END:variables
}

class CustomRender extends DefaultTableCellRenderer {

    private ExtendPoint[] clusters;

    public CustomRender(ExtendPoint[] clusters) {
	super();
	this.clusters = clusters;
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, final int row, int column) {

	if (column == 4) {
	    JPanel p = new JPanel();
	    JPanel pp = new JPanel();
//	    pp.setBounds(0,-5, 30, 20);
	    pp.setBackground(clusters[row].color.toColor());

	    p.add(pp);
	    return p;
	} else {
	    Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
	    //c.setBackground(Color.white);
	    return c;
//	    
	}
    }
}
